export const HOME_ROUTE = "/";
export const LOGIN_ROUTE = "/login";
export const REGISTER_ROUTE = "/register";
export const PRODUCT_ROUTE = "/products";
export const CART_ROUTE = "/cart";
export const DOCTORS_ROUTE = "/doctors";
export const USER_DASHBOARD_ROUTE = "/dashboard";
export const USER_DASHBOARD_ORDERS_ROUTE = "/dashboard/orders";
export const USER_DASHBOARD_APPOINTMENTS_ROUTE = "/dashboard/appointments";
export const USER_DASHBOARD_ORDER_HISTORY_ROUTE = "/dashboard/order-history";
export const USER_DASHBOARD_PAYMENTS_ROUTE = "/dashboard/payments";
export const USER_PROFILE_ROUTE = "/dashboard/profile";
export const DOCTOR_DASHBOARD_ROUTE = "/doctor/dashboard";
export const DOCTOR_APPOINTMENTS_ROUTE = "/doctor/dashboard/appointments";
export const DOCTOR_PROFILE_ROUTE = "/doctor/dashboard/profile";

// Admin Routes
export const ADMIN_DASHBOARD_ROUTE = "/admin";
export const ADMIN_USERS_ROUTE = "/admin/users";
export const ADMIN_PRODUCTS_ROUTE = "/admin/products";
export const ADMIN_PRODUCTS_NEW_ROUTE = "/admin/products/new";
export const ADMIN_PENDING_DOCTORS_ROUTE = "/admin/doctors/pending";
export const ADMIN_ALL_DOCTORS_ROUTE = "/admin/doctors";
export const ADMIN_PROFILE_ROUTE = "/admin/profile";

export const ROUTES = {
  HOME: HOME_ROUTE,
  LOGIN: LOGIN_ROUTE,
  REGISTER: REGISTER_ROUTE,
  PRODUCT: PRODUCT_ROUTE,
  CART: CART_ROUTE,
  DOCTORS: DOCTORS_ROUTE,
  USER_DASHBOARD: USER_DASHBOARD_ROUTE,
  USER_DASHBOARD_ORDERS: USER_DASHBOARD_ORDERS_ROUTE,
  USER_DASHBOARD_APPOINTMENTS: USER_DASHBOARD_APPOINTMENTS_ROUTE,
  USER_DASHBOARD_ORDER_HISTORY: USER_DASHBOARD_ORDER_HISTORY_ROUTE,
  USER_DASHBOARD_PAYMENTS: USER_DASHBOARD_PAYMENTS_ROUTE,
  USER_PROFILE: USER_PROFILE_ROUTE,
  DOCTOR_DASHBOARD: DOCTOR_DASHBOARD_ROUTE,
  DOCTOR_APPOINTMENTS: DOCTOR_APPOINTMENTS_ROUTE,
  DOCTOR_PROFILE: DOCTOR_PROFILE_ROUTE,
  // Admin
  ADMIN_DASHBOARD: ADMIN_DASHBOARD_ROUTE,
  ADMIN_USERS: ADMIN_USERS_ROUTE,
  ADMIN_PRODUCTS: ADMIN_PRODUCTS_ROUTE,
  ADMIN_PRODUCTS_NEW: ADMIN_PRODUCTS_NEW_ROUTE,
  ADMIN_PENDING_DOCTORS: ADMIN_PENDING_DOCTORS_ROUTE,
  ADMIN_ALL_DOCTORS: ADMIN_ALL_DOCTORS_ROUTE,
  ADMIN_PROFILE: ADMIN_PROFILE_ROUTE,
};
